package petshop;

import javax.swing.JOptionPane;
import java.util.ArrayList; // Importa a classe ArrayList
import java.util.List;    // Importa a interface List
/**
 *
 * @author Alexandra
 */
public class Cadastro extends javax.swing.JFrame {
    List<Animal> Clientes = new ArrayList<>();
    
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
       initComponents();
       //Tipo de Animal
       grpTipoAnimal.add(rbGato); //Gato
       grpTipoAnimal.add(rbCachorro); //Cachorro
    }
    
    //Limpar a tela
    public void limparTela(){
        txtNome.setText("");
        txtTutor.setText("");
        txtIdade.setText("00");
        rbGato.setSelected(false);
        rbCachorro.setSelected(false);
        cxVacinado.setSelected(false);
        cbGenero.setSelectedIndex(0);
        cbPlano.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTipoAnimal = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblTipoAnimal = new javax.swing.JLabel();
        rbGato = new javax.swing.JRadioButton();
        rbCachorro = new javax.swing.JRadioButton();
        lblIdade = new javax.swing.JLabel();
        txtIdade = new javax.swing.JFormattedTextField();
        lblGenero = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox<>();
        lblTutor = new javax.swing.JLabel();
        txtTutor = new javax.swing.JTextField();
        cxVacinado = new javax.swing.JCheckBox();
        lblPlano = new javax.swing.JLabel();
        cbPlano = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnOK = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");

        jPanel1.setName("pnlPainel"); // NOI18N

        lblNome.setText("Nome:");

        txtNome.setName("txtNome"); // NOI18N

        lblTipoAnimal.setText("Tipo Animal:");

        rbGato.setText("Gato");

        rbCachorro.setText("Cachorro");

        lblIdade.setText("Idade:");

        txtIdade.setText("00");
        txtIdade.setName("txtIdade"); // NOI18N

        lblGenero.setText("Gênero:");
        lblGenero.setName(""); // NOI18N

        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino" }));

        lblTutor.setText("Tutor:");

        txtTutor.setName("txtTutor"); // NOI18N

        cxVacinado.setText("Vacinado");

        lblPlano.setText("Plano de Saúde:");

        cbPlano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ouro - 89.90", "Prata - 39.90", "Bronze - 14.90" }));

        btnOK.setText("OK");
        btnOK.setName("btnOK"); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(lblTipoAnimal)
                    .addComponent(lblIdade)
                    .addComponent(lblGenero)
                    .addComponent(lblTutor)
                    .addComponent(lblPlano)
                    .addComponent(cxVacinado))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNome)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(rbGato)
                            .addGap(49, 49, 49)
                            .addComponent(rbCachorro))
                        .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTutor, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoAnimal)
                    .addComponent(rbGato)
                    .addComponent(rbCachorro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTutor)
                    .addComponent(txtTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlano)
                    .addComponent(cbPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cxVacinado)
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOK, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // Clique do Botão OK
        String nome = txtNome.getText().toString();        
        Animal pet = new Animal(nome);
        int idade = Integer.parseInt(txtIdade.
                     getText().toString());
        pet.setIdade(idade);
        //Tipo Animal
        if(rbGato.isSelected()){
            pet.setTipoAnimal("Gato");
        } else{
            pet.setTipoAnimal("Cachorro");
        }
        String genero = cbGenero.getSelectedItem().toString();
        pet.setGenero(genero);
        String tutor = txtTutor.getText();
        pet.setTutor(tutor);
        pet.setVacinado(cxVacinado.isSelected());
        String plano = cbPlano.getSelectedItem().toString();
        pet.setPlanoSaude(plano);
        //Adiciona na lista de clientes
        Clientes.add(pet);
        System.out.println(pet.toString());
        JOptionPane.showMessageDialog(null, 
                "Bichinho cadastrado com sucesso!"); 
        limparTela();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Botão Cancelar
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JComboBox<String> cbPlano;
    private javax.swing.JCheckBox cxVacinado;
    private javax.swing.ButtonGroup grpTipoAnimal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPlano;
    private javax.swing.JLabel lblTipoAnimal;
    private javax.swing.JLabel lblTutor;
    private javax.swing.JRadioButton rbCachorro;
    private javax.swing.JRadioButton rbGato;
    private javax.swing.JFormattedTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTutor;
    // End of variables declaration//GEN-END:variables
}
