package escolamusica;

/**
 *
 * @author Alexandra
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        btnAluno = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();
        mnCadastros = new javax.swing.JMenu();
        mnCadAlunos = new javax.swing.JMenuItem();
        mnListagem = new javax.swing.JMenuItem();
        mnCadastroCursos = new javax.swing.JMenuItem();
        mnListaCursos = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();
        mnSobre = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escola de Belas Artes");

        btnAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escolamusica/person.png"))); // NOI18N
        btnAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunoActionPerformed(evt);
            }
        });

        mnArquivo.setText("Arquivo");

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        mnArquivo.add(mnSair);

        jMenuBar1.add(mnArquivo);

        mnCadastros.setText("Cadastros");

        mnCadAlunos.setText("Alunos");
        mnCadAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadAlunosActionPerformed(evt);
            }
        });
        mnCadastros.add(mnCadAlunos);

        mnListagem.setText("Listagem de Alunos");
        mnListagem.setToolTipText("");
        mnListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListagemActionPerformed(evt);
            }
        });
        mnCadastros.add(mnListagem);

        mnCadastroCursos.setText("Cursos");
        mnCadastroCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastroCursosActionPerformed(evt);
            }
        });
        mnCadastros.add(mnCadastroCursos);

        mnListaCursos.setText("Listagem de Cursos");
        mnListaCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListaCursosActionPerformed(evt);
            }
        });
        mnCadastros.add(mnListaCursos);

        jMenuItem3.setText("Professores");
        jMenuItem3.setToolTipText("");
        mnCadastros.add(jMenuItem3);

        jMenuItem4.setText("Turmas");
        mnCadastros.add(jMenuItem4);

        jMenuBar1.add(mnCadastros);

        mnAjuda.setText("Ajuda");

        mnSobre.setText("Sobre");
        mnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSobreActionPerformed(evt);
            }
        });
        mnAjuda.add(mnSobre);

        jMenuBar1.add(mnAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAluno)
                .addGap(0, 367, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAluno)
                .addGap(0, 241, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadAlunosActionPerformed
        // Menu Cadastro de Alunos
        CadastroAluno cadastro = new CadastroAluno();
        cadastro.setVisible(true);
    }//GEN-LAST:event_mnCadAlunosActionPerformed

    private void mnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSobreActionPerformed
        // Menu Sobre
        Sobre sobre = new Sobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_mnSobreActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        // Sair
        dispose();
    }//GEN-LAST:event_mnSairActionPerformed

    private void btnAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunoActionPerformed
        // Cadastri de Alunos
        CadastroAluno cadastro = new CadastroAluno();
        cadastro.setVisible(true);
    }//GEN-LAST:event_btnAlunoActionPerformed

    private void mnListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListagemActionPerformed
        // TODO add your handling code here:
        ListaAlunos listagem = new ListaAlunos();
        listagem.setVisible(true);
    }//GEN-LAST:event_mnListagemActionPerformed

    private void mnCadastroCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastroCursosActionPerformed
        // TODO add your handling code here:
        CadastroCurso cadCurso = new CadastroCurso();
        cadCurso.setVisible(true);        
    }//GEN-LAST:event_mnCadastroCursosActionPerformed

    private void mnListaCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListaCursosActionPerformed
        // 
        ListaCursos listagem = new ListaCursos();
        listagem.setVisible(true);

    }//GEN-LAST:event_mnListaCursosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAluno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenuItem mnCadAlunos;
    private javax.swing.JMenuItem mnCadastroCursos;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenuItem mnListaCursos;
    private javax.swing.JMenuItem mnListagem;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JMenuItem mnSobre;
    // End of variables declaration//GEN-END:variables
}
